
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
	set(BIN_SUFFIX x64)
else()
	set(BIN_SUFFIX x86)
endif()

if(${CONFIG} STREQUAL Debug)
    file(COPY "${CMAKE_BINARY_DIR}/deps/${BIN_SUFFIX}/d/" DESTINATION "${CMAKE_BINARY_DIR}/${CONFIG}/")
else()
    file(COPY "${CMAKE_BINARY_DIR}/deps/${BIN_SUFFIX}/r/" DESTINATION "${CMAKE_BINARY_DIR}/${CONFIG}/")

endif()
